import {test,expect} from 'bun:test';
import {fadeSteps} from './fade';
test('fadeSteps interpolates rounded volumes, includes from, and waits interval until last',()=>{
  const up=fadeSteps(0,100,1000);
  expect(up[0]).toEqual({volume:0,wait:100});
  expect(up.at(-1)).toEqual({volume:100,wait:0});
  expect(up.map(s=>s.volume)).toEqual([0,10,20,30,40,50,60,70,80,90,100]);
  expect(up.slice(0,-1).every(s=>s.wait===100)).toBe(true);
  expect(fadeSteps(0,100,1000,100)).toEqual(up);
  const down=fadeSteps(100,0,500);
  expect(down[0]?.volume).toBe(100);
  expect(down.map(s=>s.volume)).toEqual([100,80,60,40,20,0]);
  expect(down.at(-1)).toEqual({volume:0,wait:0});
  expect(down.slice(0,-1).every(s=>s.wait===100)).toBe(true);
  expect(fadeSteps(40,0,0)).toEqual([{volume:0,wait:0}]);
  expect(fadeSteps(12,88,-1)).toEqual([{volume:88,wait:0}]);
  expect(fadeSteps(3,9,Number.NaN)).toEqual([{volume:9,wait:0}]);
  const custom=fadeSteps(0,10,1000,250);
  expect(custom[0]).toEqual({volume:0,wait:250});
  expect(custom.at(-1)).toEqual({volume:10,wait:0});
  expect(custom.slice(0,-1).every(s=>s.wait===250)).toBe(true);
  expect(custom.every(s=>Number.isInteger(s.volume)&&s.volume>=0&&s.volume<=100)).toBe(true);
  const clamped=fadeSteps(-20,140,400);
  expect(clamped[0]?.volume).toBe(0);
  expect(clamped.at(-1)).toEqual({volume:100,wait:0});
  expect(clamped.every(s=>Number.isInteger(s.volume)&&s.volume>=0&&s.volume<=100)).toBe(true);
  const rounded=fadeSteps(10.4,20.6,300);
  expect(rounded[0]?.volume).toBe(10);
  expect(rounded.at(-1)).toEqual({volume:21,wait:0});
  const same=fadeSteps(50,50,200);
  expect(same[0]?.volume).toBe(50);
  expect(same.at(-1)).toEqual({volume:50,wait:0});
  expect(same.every(s=>s.volume===50)).toBe(true);
  const short=fadeSteps(0,100,50);
  expect(short[0]?.volume).toBe(0);
  expect(short.at(-1)).toEqual({volume:100,wait:0});
  expect(short.slice(0,-1).every(s=>s.wait===100)).toBe(true);
  const rise=fadeSteps(20,80,800);
  for(let i=1;i<rise.length;i++)expect(rise[i]!.volume).toBeGreaterThanOrEqual(rise[i-1]!.volume);
  const fall=fadeSteps(80,20,800);
  for(let i=1;i<fall.length;i++)expect(fall[i]!.volume).toBeLessThanOrEqual(fall[i-1]!.volume);
});
