import {test,expect} from 'bun:test';
import {levenshtein,fuzzyMatch} from './fuzzy';

test('levenshtein is edit distance; fuzzyMatch ranks name+artist matches within max (default 2)',()=>{
  expect(levenshtein('','')).toBe(0);
  expect(levenshtein('abc','abc')).toBe(0);
  expect(levenshtein('','abc')).toBe(3);
  expect(levenshtein('abc','')).toBe(3);
  expect(levenshtein('kitten','sitting')).toBe(3);
  expect(levenshtein('sitting','kitten')).toBe(3);
  expect(levenshtein('book','back')).toBe(2);
  expect(levenshtein('Saturday','Sunday')).toBe(3);
  expect(levenshtein('café','cafe')).toBe(1);
  expect(levenshtein('a','A')).toBe(1);
  expect(levenshtein('🎵','🎵')).toBe(0);
  expect(levenshtein('🎵','🎶')).toBe(1);
  const insert=levenshtein('abc','abxc');
  const del=levenshtein('abxc','abc');
  const sub=levenshtein('abc','axc');
  expect(insert).toBe(1);expect(del).toBe(1);expect(sub).toBe(1);

  const q='radiohead';
  const exact={id:'0',name:'Creep',artist:'Radiohead',album:'Pablo Honey'};
  const d1={id:'1',name:'Nude',artist:'Radiohed',album:'In Rainbows'};
  const d2={id:'2',name:'Bloom',artist:'Radiohexx',album:'TKOL'};
  const d3={id:'3',name:'Silent',artist:'Radixxxad',album:'X'};
  const nameHit={id:'4',name:'Teardrop',artist:'Massive Attack',album:'Mezzanine'};
  const nameTypo={id:'5',name:'Teardropx',artist:'Massive Attack',album:'Mezzanine'};
  const police={id:'6',name:'Karma Police',artist:'Radiohead',album:'OK Computer'};
  const airbag={id:'7',name:'Airbag',artist:'Radiohead',album:'OK Computer'};
  expect(levenshtein(q,exact.artist.toLowerCase())).toBe(0);
  expect(levenshtein(q,d1.artist.toLowerCase())).toBe(1);
  expect(levenshtein(q,d2.artist.toLowerCase())).toBe(2);
  expect(levenshtein(q,d3.artist.toLowerCase())).toBeGreaterThan(2);
  expect(levenshtein('teardrop',nameHit.name.toLowerCase())).toBe(0);
  expect(levenshtein('teardrop',nameTypo.name.toLowerCase())).toBe(1);

  const mixed=[d3,d2,exact,d1];
  const ranked=fuzzyMatch(mixed,q);
  expect(ranked).toEqual([exact,d1,d2]);
  expect(ranked[0]).toBe(exact);
  expect(ranked[1]).toBe(d1);
  expect(ranked[2]).toBe(d2);
  expect(ranked.includes(d3)).toBe(false);
  expect(fuzzyMatch(mixed,q,2)).toEqual(ranked);
  expect(fuzzyMatch(mixed,q,undefined)).toEqual(ranked);
  expect(fuzzyMatch(mixed,q,NaN)).toEqual(ranked);
  expect(fuzzyMatch(mixed,q,0)).toEqual([exact]);
  expect(fuzzyMatch(mixed,q,1)).toEqual([exact,d1]);
  expect(fuzzyMatch(mixed,q,3).map(e=>e.id)).toEqual(expect.arrayContaining(['0','1','2','3']));
  expect(fuzzyMatch(mixed,'RADIOHEAD')).toEqual(ranked);
  expect(fuzzyMatch(mixed,'  RadioHead  ')).toEqual(ranked);
  expect(fuzzyMatch(mixed,'zzzzzzzz')).toEqual([]);
  expect(fuzzyMatch([],q)).toEqual([]);
  expect(fuzzyMatch(mixed,'')).toEqual(mixed);
  expect(fuzzyMatch(mixed,'   ')).toEqual(mixed);
  const copy=mixed.slice();
  fuzzyMatch(mixed,q);
  expect(mixed).toEqual(copy);

  expect(fuzzyMatch([nameHit,nameTypo],'teardrop')).toEqual([nameHit,nameTypo]);
  expect(fuzzyMatch([nameTypo,nameHit],'teardrop')[0]).toBe(nameHit);
  expect(fuzzyMatch([nameHit],'teardropx')).toEqual([nameHit]);
  expect(fuzzyMatch([police],'polce')).toEqual([police]);
  expect(fuzzyMatch([police],'karm police')).toEqual([police]);
  expect(fuzzyMatch([airbag],'airbag radiohed')).toEqual([airbag]);
  expect(fuzzyMatch([airbag,police],'airbag')[0]).toBe(airbag);
  const caseFold={id:'c',name:'  Jóga  ',artist:' BJÖRK '};
  expect(fuzzyMatch([caseFold],'joga')).toEqual([caseFold]);
  expect(fuzzyMatch([caseFold],'jóga')[0]).toBe(caseFold);
  expect(fuzzyMatch([d3],q,0)).toEqual([]);
  expect(fuzzyMatch([exact],q,-1)).toEqual([exact]);
});
