import {test,expect} from 'bun:test';
import {Keymap} from './keymap';
test('keymap parses binds, round-trips serialize, and looks up exact keys',()=>{
  expect(new Keymap().map).toEqual({});
  expect(new Keymap().lookup('q')).toBeUndefined();
  const seed={q:'quit',space:'toggle'};
  const km=new Keymap(seed);
  km.bind('q','exit');
  expect(seed.q).toBe('quit');
  expect(km.lookup('q')).toBe('exit');
  expect(km.lookup('Q')).toBeUndefined();
  expect(km.lookup(' space')).toBeUndefined();
  km.bind('s','shuffle');
  km.parse('# comment\n\nleft previous\r\nright next # skip\norphan\n+ louder');
  expect(km.lookup('left')).toBe('previous');
  expect(km.lookup('right')).toBe('next');
  expect(km.lookup('+')).toBe('louder');
  expect(km.lookup('orphan')).toBeUndefined();
  expect(km.lookup('#')).toBeUndefined();
  km.parse('q quit');
  expect(km.lookup('q')).toBe('quit');
  const copy=new Keymap();
  copy.parse(km.serialize());
  expect(copy.map).toEqual(km.map);
  expect(copy.lookup('space')).toBe('toggle');
  expect(copy.serialize()).toBe(km.serialize());
  const one=new Keymap();
  one.parse('space toggle');
  expect(one.serialize()).toBe('space toggle');
  expect(one.lookup('space')).toBe('toggle');
});
