import {test,expect} from 'bun:test';
import {PaletteHistory} from './palette-history';
test('PaletteHistory ignores blanks, unique newest-first cap 20, previous/next walk ends',()=>{
  const h=new PaletteHistory();
  expect(h.items).toEqual([]);expect(h.previous()).toBeUndefined();expect(h.next()).toBeUndefined();
  for(const q of ['','  ','\t','\n',' \t\n '])h.push(q);
  expect(h.items).toEqual([]);expect(h.previous()).toBeUndefined();
  h.push('alpha');h.push(' beta ');h.push('\ngamma\t');h.push('alpha');h.push('  beta');
  expect(h.items).toEqual(['beta','alpha','gamma']);
  expect(h.previous()).toBe('beta');expect(h.previous()).toBe('alpha');expect(h.previous()).toBe('gamma');
  expect(h.previous()).toBeUndefined();expect(h.previous()).toBeUndefined();
  expect(h.next()).toBe('alpha');expect(h.next()).toBe('beta');expect(h.next()).toBeUndefined();expect(h.next()).toBeUndefined();
  expect(h.previous()).toBe('beta');
  h.push('delta');
  expect(h.items).toEqual(['delta','beta','alpha','gamma']);
  expect(h.next()).toBeUndefined();expect(h.previous()).toBe('delta');expect(h.previous()).toBe('beta');
  h.push('delta');expect(h.items).toEqual(['delta','beta','alpha','gamma']);expect(h.previous()).toBe('delta');
  const full=new PaletteHistory();
  const queries=Array.from({length:25},(_,i)=>`q${i+1}`);
  for(const q of queries)full.push(q);
  expect(full.items).toHaveLength(20);
  expect(full.items).toEqual(queries.slice(-20).reverse());
  expect(full.items.at(-1)).toBe('q6');expect(full.items).not.toContain('q5');
  full.push('q6');expect(full.items).toHaveLength(20);expect(full.items[0]).toBe('q6');expect(full.items.at(-1)).toBe('q7');
  expect(full.previous()).toBe('q6');expect(full.previous()).toBe('q25');
  const one=new PaletteHistory();one.push('only');
  expect(one.previous()).toBe('only');expect(one.previous()).toBeUndefined();expect(one.next()).toBeUndefined();
  expect(one.next()).toBeUndefined();expect(one.previous()).toBe('only');
  const spaces=new PaletteHistory();spaces.push('  a  b  ');spaces.push('a  b');
  expect(spaces.items).toEqual(['a  b']);
  const cased=new PaletteHistory();cased.push('Next');cased.push('next');
  expect(cased.items).toEqual(['next','Next']);
});
