import {test,expect} from 'bun:test';
import {QuitGuard} from './quit-guard';
test('QuitGuard arms first press, confirms within windowMs (default 1500), rearms after window, reset clears',()=>{
  const g=new QuitGuard();
  expect(g.press(0)).toBe(false);
  expect(g.press(1499)).toBe(true);
  expect(g.press(10_000)).toBe(false);
  expect(g.press(11_499)).toBe(true);
  expect(g.press(20_000)).toBe(false);
  expect(g.press(21_500)).toBe(false);
  expect(g.press(22_999)).toBe(true);
  expect(g.press(30_000)).toBe(false);
  g.reset();
  expect(g.press(30_001)).toBe(false);
  expect(g.press(31_500)).toBe(true);
  const r=new QuitGuard();
  expect(r.press(0)).toBe(false);
  r.reset();
  expect(r.press(10)).toBe(false);
  expect(r.press(20)).toBe(true);
  r.reset();
  expect(r.press(20)).toBe(false);
  const tight=new QuitGuard(50);
  expect(tight.press(0)).toBe(false);
  expect(tight.press(49)).toBe(true);
  expect(tight.press(100)).toBe(false);
  expect(tight.press(150)).toBe(false);
  expect(tight.press(199)).toBe(true);
  const live=new QuitGuard(10_000);
  expect(live.press()).toBe(false);
  expect(live.press()).toBe(true);
  live.reset();
  expect(live.press()).toBe(false);
  expect(live.press()).toBe(true);
});
