import {test,expect} from 'bun:test';
import {RateLimit} from './rate-limit';
test('RateLimit allows max hits per sliding window, frees slots as timestamps expire, denied calls do not consume',()=>{
  const r=new RateLimit(3,1000);
  expect(r.allow(0)).toBe(true);
  expect(r.allow(1)).toBe(true);
  expect(r.allow(2)).toBe(true);
  expect(r.allow(2)).toBe(false);
  expect(r.allow(999)).toBe(false);
  expect(r.allow(1000)).toBe(true);
  expect(r.allow(1000)).toBe(false);
  expect(r.allow(1001)).toBe(true);
  expect(r.allow(1001)).toBe(false);
  expect(r.allow(1002)).toBe(true);
  expect(r.allow(1002)).toBe(false);
  expect(r.allow(1999)).toBe(false);
  expect(r.allow(2000)).toBe(true);
  expect(r.allow(2001)).toBe(true);
  expect(r.allow(2002)).toBe(true);
  expect(r.allow(2002)).toBe(false);
  const once=new RateLimit(1,100);
  expect(once.allow(0)).toBe(true);
  expect(once.allow(99)).toBe(false);
  expect(once.allow(100)).toBe(true);
  expect(once.allow(100)).toBe(false);
  expect(once.allow(199)).toBe(false);
  expect(once.allow(200)).toBe(true);
  const burst=new RateLimit(2,50);
  expect(burst.allow(10)).toBe(true);
  expect(burst.allow(10)).toBe(true);
  expect(burst.allow(10)).toBe(false);
  expect(burst.allow(59)).toBe(false);
  expect(burst.allow(60)).toBe(true);
  expect(burst.allow(60)).toBe(true);
  expect(burst.allow(60)).toBe(false);
  const live=new RateLimit(1,10_000);
  expect(live.allow()).toBe(true);
  expect(live.allow()).toBe(false);
  const other=new RateLimit(5,1000);
  for(let i=0;i<5;i++)expect(other.allow(0)).toBe(true);
  expect(other.allow(0)).toBe(false);
  expect(other.allow(999)).toBe(false);
  expect(other.allow(1000)).toBe(true);
  const none=new RateLimit(0,100);
  expect(none.allow(0)).toBe(false);
  expect(none.allow(100)).toBe(false);
});
