import {test,expect} from 'bun:test';
import {RingBuffer} from './ring';
test('RingBuffer keeps insertion order, last() is newest, and push drops oldest past limit',()=>{
  const buf=new RingBuffer<string>(3);
  expect(buf.values()).toEqual([]);
  expect(buf.last()).toBeUndefined();
  buf.push('a');
  expect(buf.values()).toEqual(['a']);
  expect(buf.last()).toBe('a');
  buf.push('b');buf.push('c');
  expect(buf.values()).toEqual(['a','b','c']);
  expect(buf.last()).toBe('c');
  buf.push('d');
  expect(buf.values()).toEqual(['b','c','d']);
  expect(buf.last()).toBe('d');
  buf.push('e');buf.push('f');
  expect(buf.values()).toEqual(['d','e','f']);
  expect(buf.last()).toBe('f');
  const snap=buf.values();
  snap.push('mutated');
  snap[0]='x';
  expect(buf.values()).toEqual(['d','e','f']);
  expect(buf.last()).toBe('f');
  buf.push('d');
  expect(buf.values()).toEqual(['e','f','d']);
  expect(buf.last()).toBe('d');
  const one=new RingBuffer<number>(1);
  expect(one.last()).toBeUndefined();
  one.push(1);expect(one.values()).toEqual([1]);expect(one.last()).toBe(1);
  one.push(2);one.push(3);
  expect(one.values()).toEqual([3]);expect(one.last()).toBe(3);
  const none=new RingBuffer<string>(0);
  none.push('z');none.push('y');
  expect(none.values()).toEqual([]);expect(none.last()).toBeUndefined();
  for(const limit of [NaN,Infinity,-Infinity,-1,-0.4,0.4]){
    const dead=new RingBuffer<string>(limit);
    dead.push('keep');
    expect(dead.values()).toEqual([]);
    expect(dead.last()).toBeUndefined();
  }
  const frac=new RingBuffer<string>(2.9);
  frac.push('a');frac.push('b');frac.push('c');
  expect(frac.values()).toEqual(['b','c']);
  expect(frac.last()).toBe('c');
  const ids=new RingBuffer<{id:string}>(2);
  const t1={id:'t1'};const t2={id:'t2'};const t3={id:'t3'};
  ids.push(t1);ids.push(t2);ids.push(t3);
  expect(ids.values()).toEqual([t2,t3]);
  expect(ids.last()).toBe(t3);
  expect(ids.values()[0]).toBe(t2);
  const many=new RingBuffer<number>(5);
  for(let i=0;i<20;i++)many.push(i);
  expect(many.values()).toEqual([15,16,17,18,19]);
  expect(many.last()).toBe(19);
  expect(many.values()).toHaveLength(5);
});
