import {test,expect} from 'bun:test';
import {TtlCache} from './ttl-cache';
test('TtlCache get returns value until ttl, then undefined; keys independent; set refreshes',()=>{
  const cache=new TtlCache<string>(1000);
  expect(cache.get('miss',0)).toBeUndefined();
  cache.set('fail','https://i.scdn.co/bad.jpg',0);
  expect(cache.get('fail',0)).toBe('https://i.scdn.co/bad.jpg');
  expect(cache.get('fail',999)).toBe('https://i.scdn.co/bad.jpg');
  expect(cache.get('fail',1000)).toBeUndefined();
  expect(cache.get('fail',1500)).toBeUndefined();
  cache.set('fail','https://i.scdn.co/retry.jpg',1000);
  expect(cache.get('fail',1000)).toBe('https://i.scdn.co/retry.jpg');
  expect(cache.get('fail',1999)).toBe('https://i.scdn.co/retry.jpg');
  expect(cache.get('fail',2000)).toBeUndefined();
  cache.set('ok','https://i.scdn.co/ok.jpg',500);
  cache.set('fail','https://i.scdn.co/other.jpg',800);
  expect(cache.get('ok',500)).toBe('https://i.scdn.co/ok.jpg');
  expect(cache.get('fail',800)).toBe('https://i.scdn.co/other.jpg');
  expect(cache.get('ok',1499)).toBe('https://i.scdn.co/ok.jpg');
  expect(cache.get('fail',1799)).toBe('https://i.scdn.co/other.jpg');
  expect(cache.get('ok',1500)).toBeUndefined();
  expect(cache.get('fail',1800)).toBeUndefined();
  const flags=new TtlCache<boolean>(50);
  flags.set('url',false,0);
  expect(flags.get('url',0)).toBe(false);
  expect(flags.get('url',49)).toBe(false);
  expect(flags.get('url',50)).toBeUndefined();
  flags.set('url',true,50);
  expect(flags.get('url',50)).toBe(true);
  expect(flags.get('url',99)).toBe(true);
  expect(flags.get('url',100)).toBeUndefined();
  const nums=new TtlCache<number>(10);
  nums.set('n',0,0);
  expect(nums.get('n',9)).toBe(0);
  expect(nums.get('n',10)).toBeUndefined();
  const empty=new TtlCache<string>(5);
  empty.set('e','',0);
  expect(empty.get('e',4)).toBe('');
  expect(empty.get('e',5)).toBeUndefined();
  const live=new TtlCache<string>(10_000);
  live.set('k','v');
  expect(live.get('k')).toBe('v');
  expect(live.get('missing')).toBeUndefined();
});
